import React from "react";
import { Box, Typography } from "@mui/material";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import CircleIcon from "@mui/icons-material/Circle";
import { useTheme } from "@mui/material";

const TermsComponent = () => {
  const theme = useTheme();
  const items = [
    "Account means a unique account created for You to access our Serviceor parts of our Service.",
    "        Company (referred to as either the Company, We, Us or Our in this Agreement) refers to Everfriends.ai.",
    "        Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. ",
    "        Country refers to United States of America ",
    "        Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
    "        Personal Data is any information that relates to an identified or identifiable individual. ",
    "        Service refers to the Website. ",
    "        Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to assist the Company in analyzing how the Service is used. ",
    "        Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). ",
    "        Website refers to everfriends.ai ",
    "        You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
  ];

  return (
    <Box
      sx={{
        height: "100%",
        width: "100%",
        boxSizing: "border-box",
        paddingRight: "1rem",
        paddingBottom: "1rem",
        paddingLeft: { xs: "1rem", sm: "1rem", md: "0" },
      }}
    >
      <Box
        sx={{
          boxSizing: "border-box",
          borderRadius: "15px",
          background: "rgba(255, 255, 255, 1)",
          boxShadow: "0px 4px 15px 0px rgba(0, 0, 0, 0.06)",
          height: "100%",
          overflowY: "auto",
          padding: "2rem",
          color: "#2B2B2B",
        }}
      >
        <Typography variant="body1" sx={{ lineHeight: "30px" }}>
          This Policy describes Our policies and procedures on the collection,
          use, and disclosure of Your information when You use the Service and
          tells You about Your privacy rights and how the law protects You.
        </Typography>
        <Typography variant="body1" sx={{ lineHeight: "30px" }}>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy. Interpretation and Definitions
        </Typography>
        <Typography variant="body1" sx={{ lineHeight: "30px" }}>
          Interpretation and Definitions
        </Typography>
        <Typography variant="body1" sx={{ lineHeight: "30px" }}>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in the plural.
        </Typography>
        <Typography variant="h5" sx={{ fontWeight: "600", margin: "2rem 0" }}>
          Definitions
        </Typography>
        <Typography variant="body1" sx={{ margin: "1rem 0" }}>
          For the purposes of this Privacy Policy:
        </Typography>
         
        <List>
          {items.map((item, index) => (
            <ListItem key={index} disablePadding>
              <CircleIcon
                sx={{
                  color: "black",
                  fontSize: 6,
                  marginLeft: "2rem",
                  [theme.breakpoints.down("md")]: {
                    marginLeft: "0rem",
                  },
                }}
              />
              <ListItemText
                primary={item}
                sx={{
                  marginLeft: "1rem",
                  [theme.breakpoints.down("sm")]: {
                    fontSize: "0.8rem",
                  },
                }}
              />
            </ListItem>
          ))}
        </List>
      </Box>
    </Box>
  );
};

export default TermsComponent;
